spring.application.name=smarttutor
# Enable the web-based H2 database console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Settings
# spring.datasource.url=jdbc:h2:file:~/Documents/test
spring.datasource.url=jdbc:h2:file:/ssja/backend/h2/ssja
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password= 
server.port=9090

# JPA / Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

