'use strict';
const sessionUser=Auth.getUser();
const sessionTutor=sessionUser?.role==='TUTOR';
const base=window.SMART_TUTOR_API_URL;
let announcementId=null;
function sessionMessage(text,error=false){const el=document.getElementById('message');el.textContent=text;el.className=`alert ${error?'alert-danger':'alert-success'}`;}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function sessionApi(path,method='GET',body){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json','Authorization':'Bearer '+sessionUser.sessionToken},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(response.status===401?'Please log out and log in again to activate sessions.':data.message||data.detail||'Request failed');return data;}
async function refreshSessions(){
 try{const rows=await sessionApi('/api/sessions');document.getElementById('slots').innerHTML=rows.length?rows.map(r=>{const s=r.session;return `<div class="col-md-6"><article class="card p-4 h-100"><div class="d-flex justify-content-between"><span class="badge text-bg-light">${s.kind==='ONE_TO_ONE'?'One-to-one':'Course session'} · ${esc(s.mode)}</span><span>${s.cancelled?'Cancelled':r.mine?(r.approvalStatus==='PENDING'?'Awaiting tutor approval':'Your booking'):r.available?'Available':'Unavailable'}</span></div><h3 class="h5 mt-3">${esc(s.title)}</h3><p class="mb-1">${esc(r.tutorName)}</p><p>${esc(s.date)} · ${esc(s.startTime)}–${esc(s.endTime)} IST</p><p class="text-secondary">${esc(s.details)}</p><p class="text-secondary">${r.studentAddress?`Student location: ${esc(r.studentAddress)}`:""}</p><p class="small">${r.count} student(s) booked</p>${sessionTutor&&r.approvalStatus==='PENDING'&&!s.cancelled?`<p>Home visit request — awaiting your decision</p><div class="mb-2"><button class="btn btn-success me-2" data-action="accept" data-id="${s.id}">Accept request</button><button class="btn btn-outline-danger" data-action="reject" data-id="${s.id}">Reject request</button></div>`:''}${sessionTutor?(!s.cancelled?`<button class="btn btn-outline-success" data-action="announce" data-id="${s.id}" data-title="${esc(s.title)}">Notify students / cancel session</button>`:''):r.mine&&!s.cancelled?`<button class="btn btn-outline-danger" data-action="release" data-id="${s.id}">Cancel my booking</button>`:r.available?`${s.mode==='OFFLINE'&&s.kind==='ONE_TO_ONE'?`<label for="address-${s.id}">Your address — tutor will visit you</label><textarea id="address-${s.id}" maxlength="2000" class="form-control mb-2" placeholder="House, street, area, city and PIN code"></textarea>`:''}<button class="btn btn-success" data-action="book" data-id="${s.id}">Book this slot</button>`:''}</article></div>`;}).join(''):'<p>No sessions published yet.</p>';
 if(!sessionTutor){const notes=await sessionApi('/api/sessions/notifications');document.getElementById('unread').textContent=notes.filter(n=>!n.read).length;document.getElementById('notes').innerHTML=notes.length?notes.map(n=>`<article class="card notification p-3 mb-2"><p class="mb-1">${esc(n.message)}</p><small class="text-secondary">${esc(n.createdAt)}</small>${!n.read?`<button class="btn btn-sm btn-outline-success mt-2 align-self-start" data-read="${n.id}">Mark as read</button>`:''}</article>`).join(''):'<p>No notifications yet.</p>';}
 }catch(e){sessionMessage(e.message,true);}
}
async function initSessions(){
 if(!sessionUser||!['TUTOR','STUDENT'].includes(sessionUser.role)){location.href='login.html';return;}
 document.getElementById('back').href=sessionTutor?'tutor.html':'student.html';document.getElementById(sessionTutor?'publish':'inbox').classList.remove('d-none');document.getElementById('hint').textContent=sessionTutor?'Publish a group session to notify everyone enrolled in its course, or a personal slot for one student.':'Personal slots accept one student. Group sessions require an active course enrollment.';
 if(!sessionUser.sessionToken){sessionMessage('Please log out and log in again once to activate the new features.',true);return;}
 if(sessionTutor)document.getElementById('courseBookingLink').hidden=true;
 if(sessionTutor){try{const response=await fetch(base+'/api/courses');if(!response.ok)throw new Error('Could not load courses');const raw=await response.json();const courses=Array.isArray(raw)?raw:raw.data||[];for(const c of courses.filter(c=>String(c.tutor?.id)===String(sessionUser.id))){const o=document.createElement('option');o.value=c.id;o.textContent=c.name;document.getElementById('courseId').append(o);}}catch(e){sessionMessage(e.message,true);}}
 await refreshSessions();setInterval(()=>{if(!document.hidden)refreshSessions();},15000);
}
document.getElementById('refresh').onclick=refreshSessions;
document.getElementById('slotForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));data.courseId=data.courseId?Number(data.courseId):null;await sessionApi('/api/sessions','POST',data);e.target.reset();updateSessionDetails();sessionMessage('Timeslot published.');await refreshSessions();}catch(err){sessionMessage(err.message,true);}finally{button.disabled=false;}};
document.getElementById('slots').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='announce'){announcementId=b.dataset.id;document.getElementById('selectedTitle').textContent=b.dataset.title;document.getElementById('announcement').classList.remove('d-none');document.getElementById('announcement').scrollIntoView({behavior:'smooth'});return;}if(['accept','reject'].includes(b.dataset.action)){b.disabled=true;try{await sessionApi(`/api/sessions/${b.dataset.id}/decision`,'POST',{accept:b.dataset.action==='accept'});sessionMessage(b.dataset.action==='accept'?'Home visit confirmed.':'Request declined. Student notified.');await refreshSessions();}catch(err){sessionMessage(err.message,true);b.disabled=false;}return;}const address=document.getElementById(`address-${b.dataset.id}`);if(b.dataset.action==='book'&&address&&!address.value.trim()){sessionMessage('Enter your full address so the tutor can visit you.',true);address.focus();return;}b.disabled=true;try{await sessionApi(`/api/sessions/${b.dataset.id}/book`,b.dataset.action==='release'?'DELETE':'POST',b.dataset.action==='book'?{studentAddress:address?.value.trim()}:undefined);sessionMessage(b.dataset.action==='release'?'Your booking is cancelled.':address?'Request sent. Your booking will be confirmed after the tutor accepts.':'Session booked successfully.');await refreshSessions();}catch(err){sessionMessage(err.message,true);b.disabled=false;}};
document.getElementById('announceForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const result=await sessionApi(`/api/sessions/${announcementId}/announce`,'POST',{message:document.getElementById('reason').value,cancel:document.getElementById('cancelSession').checked});sessionMessage(`Notification saved for ${result.recipients} enrolled student(s).`);e.target.reset();document.getElementById('announcement').classList.add('d-none');await refreshSessions();}catch(err){sessionMessage(err.message,true);}finally{b.disabled=false;}};
document.getElementById('closeAnnouncement').onclick=()=>document.getElementById('announcement').classList.add('d-none');
document.getElementById('notes').onclick=async e=>{const b=e.target.closest('[data-read]');if(!b)return;try{await sessionApi(`/api/sessions/notifications/${b.dataset.read}/read`,'PATCH');await refreshSessions();}catch(err){sessionMessage(err.message,true);}};
function updateSessionDetails(){const home=document.getElementById('mode').value==='OFFLINE'&&document.getElementById('kind').value==='ONE_TO_ONE';const details=document.getElementById('details');details.required=!home;details.disabled=home;document.querySelector('label[for="details"]').textContent=home?'Tutor visits student — address collected when booking':document.getElementById('mode').value==='OFFLINE'?'Tutor venue address — students come here':'Online meeting link';}
document.getElementById('mode').onchange=updateSessionDetails;
document.getElementById('kind').onchange=updateSessionDetails;
updateSessionDetails();
initSessions();
